# Generated by Django 3.1.2 on 2020-10-05 20:31

from django.db import migrations, models
import django.db.models.deletion
import mesika_utils.RandomTransactionIds


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateInformation',
            fields=[
                ('corporate_uuid', models.CharField(default=mesika_utils.RandomTransactionIds.generate_sso_token, max_length=250, primary_key=True, serialize=False, unique=True)),
                ('corporate', models.CharField(max_length=50)),
                ('status', models.CharField(default='ACTIVE', max_length=80)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuickBooksToken',
            fields=[
                ('token_uuid', models.CharField(default=mesika_utils.RandomTransactionIds.generate_sso_token, max_length=250, primary_key=True, serialize=False, unique=True)),
                ('refresh_token', models.CharField(max_length=100)),
                ('access_token', models.TextField(max_length=3000)),
                ('token_type', models.CharField(max_length=100)),
                ('access_token_expire', models.CharField(max_length=100)),
                ('refresh_token_expire', models.CharField(max_length=100)),
                ('id_token', models.CharField(max_length=100)),
                ('realm_id', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_uuid', to='quickbooks.corporateinformation')),
            ],
        ),
    ]
