# Generated by Django 3.1.2 on 2020-10-05 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickbookstoken',
            name='id_token',
        ),
    ]
